### PR TITLE
Domain Check

### PR DESCRIPTION
**Pull request by Leowisd**
Has googled but didn't find other jar to get email domain, so use method from EmailService

licensed-domains: updated
account-approval-whitelist: no need 

token-usage-check and token-usage-check-whitelist seem don't have user domain related operations. 

PS. Not sure why readme file shows up...

### CODE REVIEW

**Comment by zhx828** [comment]
@Leowisd try to do a rebase with the latest master

**Comment by zhx828** [comment]
This fixes https://github.com/oncokb/oncokb/issues/2111

@Leowisd I saw you linked the ZenHub, that great! But unfortunately you have to mention the issue in the comment in order to link the pr to the issue as well for github feature.

**Comment by zhx828** [comment]
We also use different label to generate the release note 
Full list of labels related to release: https://github.com/oncokb/oncokb-public/blob/master/.github/release-drafter.yml
The action we are using https://github.com/release-drafter/release-drafter

**Comment by Leowisd** [comment]
@zhx828 Already rebase

**Comment by zhx828** [comment]
@Leowisd it does not seem right in the git history though

**Comment by Leowisd** [comment]
Maybe I could close this pull request and submit again.

**Pull request closed without merging**
